(function(){
  var APP='https://apps.apple.com/us/app/concerto-show-go/id6744903414';
  function mountHeader(){
    document.querySelectorAll('body > nav.nav,body > nav.topbar,body > header.site-header').forEach(function(n){n.remove()});
    var path=(location.pathname.replace(/\.html$/,'').replace(/\/$/,'')||'/');
    var h=document.createElement('header');h.className='site-header';
    function a(label,href){var active=path===href||((href==='/venues'||href==='/tours'||href==='/setlists')&&path.indexOf(href.slice(0,-1))===0);return '<a '+(active?'class="active" ':'')+'href="'+href+'">'+label+'</a>'}
    h.innerHTML='<div class="site-shell wide header-inner"><a class="site-logo" href="/" aria-label="Concerto home"><img src="/img/lockup.png" alt="Concerto"></a><nav class="site-nav" aria-label="Main">'+a('Venues','/venues')+a('Tours','/tours')+a('Setlists','/setlists')+a('Near Me','/near-me')+a('Concerto+','/premium')+a('Partners','/partners')+'</nav><div class="header-actions"><a class="header-text-link" href="/search">Search</a><a class="header-cta" href="'+APP+'" target="_blank" rel="noopener">Get the App</a><button class="menu-btn" aria-label="Open menu">☰</button></div></div><nav class="mobile-nav site-shell" aria-label="Mobile">'+a('Venues','/venues')+a('Tours','/tours')+a('Setlists','/setlists')+a('Near Me','/near-me')+a('Concerto+','/premium')+a('Perks','/perks')+a('Partners','/partners')+'<a href="/about">About</a><a class="header-cta" href="'+APP+'">Get the App</a></nav>';
    document.body.insertBefore(h,document.body.firstChild);
    var b=h.querySelector('.menu-btn'),m=h.querySelector('.mobile-nav');if(b)b.onclick=function(){m.classList.toggle('open');b.textContent=m.classList.contains('open')?'×':'☰'};
  }
  function mountFooter(){
    document.querySelectorAll('body > footer,footer.concerto-footer').forEach(function(n){n.remove()});
    var f=document.createElement('footer');f.className='site-footer';
    f.innerHTML='<div class="site-shell footer-top"><div class="footer-brand"><img src="/img/lockup.png" alt="Concerto"><h2>From the Concert to the City®</h2><p>The concert companion for the show, the venue, and everything around it.</p></div><div class="footer-nav"><div class="footer-col"><h3>Discover</h3><a href="/venues">Venues</a><a href="/tours">Tours</a><a href="/setlists">Setlists</a><a href="/near-me">Near Me</a><a href="/perks">Perks</a></div><div class="footer-col"><h3>Product</h3><a href="/premium">Concerto+</a><a href="/bagcheck">AI Bag Check</a><a href="/help">Help Center</a><a href="/faq">FAQ</a></div><div class="footer-col"><h3>Company</h3><a href="/about">About</a><a href="/press">Press & Media</a><a href="/investors">Investors</a><a href="/contact">Contact</a></div><div class="footer-col"><h3>Work With Us</h3><a href="/partners">Partners</a><a href="/creators">Creators</a><a href="https://instagram.com/theconcertoapp" target="_blank" rel="noopener">Instagram</a><a href="https://www.tiktok.com/@theconcertoapp" target="_blank" rel="noopener">TikTok</a><a href="https://www.youtube.com/@theconcertoapp" target="_blank" rel="noopener">YouTube</a></div></div></div><div class="site-shell footer-bottom"><span>© 2026 Concerto. Independent from artists, venues, teams and promoters.</span><div class="footer-bottom-links"><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div></div>';
    document.body.appendChild(f);
  }
  function norm(x){return (x||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'')}
  function setImg(el,src,alt){if(!src)return;var im=new Image();im.alt=alt||'';im.loading='lazy';im.onload=function(){el.querySelectorAll('img').forEach(function(x){x.remove()});el.insertBefore(im,el.firstChild)};im.src=src}
  document.addEventListener('DOMContentLoaded',function(){
    document.body.classList.add('public-site');mountHeader();mountFooter();
    document.querySelectorAll('[data-vphoto]').forEach(function(el){var p=new URLSearchParams({name:el.dataset.vname||'',city:el.dataset.vcity||'',lat:el.dataset.vlat||'',lng:el.dataset.vlng||''});fetch('/.netlify/functions/venue-photo?'+p).then(function(r){return r.ok?r.json():null}).then(function(d){if(d&&d.src)setImg(el,d.src,el.dataset.vname)}).catch(function(){})});
    document.querySelectorAll('[data-artist]').forEach(function(el){var artist=el.dataset.artist;if(!artist)return;var p=new URLSearchParams({keyword:artist,classificationName:'Music',size:'3',sort:'date,asc',startDateTime:new Date().toISOString().replace(/\.\d+Z$/,'Z')});fetch('/.netlify/functions/tm/events.json?'+p).then(function(r){return r.ok?r.json():null}).then(function(d){var es=d&&d._embedded&&d._embedded.events||[];var target=norm(artist);var e=es.find(function(x){return x.name&&norm(x.name).indexOf(target)!==-1})||es[0];if(e&&e.images&&e.images.length){var wide=e.images.filter(function(i){return i.ratio==='16_9'});var pool=wide.length?wide:e.images;pool.sort(function(a,b){return (b.width||0)-(a.width||0)});setImg(el,pool[0].url,artist)}}).catch(function(){})});
    document.querySelectorAll('[data-filter-target]').forEach(function(input){var sel=input.getAttribute('data-filter-target');var items=[].slice.call(document.querySelectorAll(sel));input.addEventListener('input',function(){var q=norm(input.value);items.forEach(function(item){item.style.display=!q||norm(item.textContent).indexOf(q)!==-1?'':'none'})})});
  });
})();
