#!/usr/bin/env python3
"""About, Creators, Contact, and FAQ on the V6 system. FAQ answers live in
scripts/faq.json (edit there); the contact form is kept verbatim in
scripts/forms/contact.html. Help stays hand-written in help.html."""
import html, json, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / 'scripts'))
from public_chrome import header_html, page_end, HEAD_ASSETS, product_screen, photo_slot, APP, SITE

def e(x): return html.escape(str(x or ''), quote=True)
def head(title, desc, canonical, extra=''):
    return (f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="apple-itunes-app" content="app-id=6744903414"><title>{e(title)}</title><meta name="description" content="{e(desc)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="{SITE+canonical}"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(desc)}"><meta property="og:type" content="website"><meta property="og:url" content="{SITE+canonical}"><meta property="og:image" content="{SITE}/ConcertoSocialPreview.png"><meta property="og:site_name" content="Concerto"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="{SITE}/ConcertoSocialPreview.png"><link rel="icon" href="/favicon.ico" sizes="any"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="apple-touch-icon" href="/apple-touch-icon.png">{HEAD_ASSETS}{extra}</head><body class="public-site">') + header_html(canonical)
def screen(name, alt): return f'<div class="device"><div class="iphone-screen"><img src="{product_screen(name)}" width="941" height="2048" alt="{e(alt)}" loading="lazy"></div></div>'

venues = json.loads((ROOT / 'data/venues.json').read_text()); tours = json.loads((ROOT / 'data/tours.json').read_text())
setlists = json.loads((ROOT / 'setlists.json').read_text()); live = sum(1 for k, v in setlists.items() if v.get('songs'))

# ---------------------------------------------------------------- About
about = head('About Concerto | From the Concert to the City®', 'Concerto connects the concert, venue, and city around it into one trusted show-night experience. Verified venue guides, tours and setlists, Near Me, Your Night, and Concerto+.', '/about') + f'''<main>
<section class="hero-public"><div class="site-shell wide hero-grid"><div class="hero-copy"><p class="eyebrow">About Concerto</p><h1>The concert is one part of the night.</h1><p class="lead">Concerto connects the show, the venue, and the city around it. Save a show and the scattered questions around the night become one experience: what the venue allows, how to get there, what the artist has been playing, where to eat, what the weather looks like, and how to get home.</p><div class="hero-actions"><a class="btn-primary" href="{APP}">Get Concerto for iPhone</a><a class="btn-secondary" href="/venues">Explore venue guides</a></div><div class="hero-proof"><div class="proof"><strong>{len(venues)}</strong><span>verified venue guides</span></div><div class="proof"><strong>{len(tours)}</strong><span>tour guides</span></div><div class="proof"><strong>{live}</strong><span>live setlists</span></div></div></div><div class="device-stage single">{screen('home', 'Concerto Home with the next show countdown')}</div></div></section>
<section class="story-section"><div class="site-shell"><div class="section-head"><p class="eyebrow">The problem</p><div><h2>Most concert apps stop once you know the show exists.</h2><p>Buying the ticket is the easy part. Then come the questions: Can I bring this bag? Where should I park? Where are we eating? How early do I need to leave? What songs should I know? The answers exist, but they live across venue sites, maps, review apps, ticketing pages, weather apps, and group chats.</p></div></div><div class="story-grid"><article class="story-card light"><span class="number">Discover</span><h3>Find the show.</h3><p>Near Me, tours, venue guides, and search answer what is happening and where.</p></article><article class="story-card sand"><span class="number">Save</span><h3>Make it your night.</h3><p>A saved show becomes a countdown and a show-specific destination instead of another bookmark.</p></article><article class="story-card dark"><span class="number">Go</span><h3>Know what matters.</h3><p>Venue rules, timing, weather, nearby places, setlists, arrival, and getting home stay connected to the same show.</p></article></div></div></section>
{photo_slot('arrival','Fans arriving at the venue gates')}
<section class="proof-band"><div class="site-shell"><div class="section-head"><p class="eyebrow">The Concerto standard</p><div><h2>Verified beats comprehensive.</h2><p>Critical venue information is researched from official sources and dated so you can see when Concerto last confirmed it. If a venue has not published something, Concerto says so instead of filling the gap with a guess. The product is not just information. It is confidence about what is actually true.</p></div></div><div class="traction-grid"><div class="traction"><strong>8</strong><span>verified sections in every venue guide: bag policy, parking, rideshare, concessions, accessibility, re-entry, ticket pickup, gates</span></div><div class="traction"><strong>Dated</strong><span>every critical fact shows when it was last confirmed</span></div><div class="traction"><strong>Official</strong><span>sources first, with the link to the venue's own page</span></div><div class="traction"><strong>Independent</strong><span>from artists, venues, teams, and promoters</span></div></div></div></section>
<section class="section"><div class="shell split"><div><p class="eyebrow">Free and Concerto+</p><h2>Free tells you what to know. Concerto+ helps decide what to do with it.</h2></div><div><p class="lead">Free Concerto is the trustworthy layer: venue guides, tours, setlists, Near Me, saved shows, and nearby places. Concerto+ is the personalized layer: Your Night planned around the show you saved, Plan My Night timing, AI Bag Check, and alerts that react when conditions change.</p><div class="hero-actions"><a class="btn-primary" href="/premium">See Concerto+</a><a class="btn-secondary" href="/perks">See Concerto Perks</a></div></div></div></section>
<section class="section"><div class="shell split"><div><p class="eyebrow">Founder</p><h2>Built from the fan problem outward.</h2></div><div><p class="lead">Concerto was founded by Jayce Wells in Dallas-Fort Worth after seeing how fragmented concert-night planning remained even after tickets were purchased. It started as a set of venue guides and grew into the iPhone app and this site, both running on the same data. The goal has not changed: make the night around the concert feel as considered as the concert itself.</p><div class="hero-actions"><a class="btn-secondary" href="/press">Press and media</a><a class="btn-secondary" href="/investors">Investors</a><a class="btn-secondary" href="/contact">Contact</a></div></div></div></section>
<section class="cta-band"><div class="site-shell"><p class="eyebrow">From the Concert to the City®</p><h2>Planning the night should be as easy as enjoying it.</h2><p>Save the show and let Concerto keep everything around the night connected.</p><div class="hero-actions"><a class="btn-primary" href="{APP}">Get the App</a><a class="btn-secondary" href="/near-me">See what is near you</a></div></div></section>
</main>''' + page_end()
(ROOT / 'about.html').write_text(about)

# ---------------------------------------------------------------- Creators
creators = head('Creators | Collaborate with Concerto', 'Concerto works with music, city, food, and travel creators on content fans can actually use before, around, and after the show. Pitch an idea.', '/creators') + f'''<main>
<section class="page-hero-v4"><div class="site-shell"><p class="eyebrow">Creators</p><h1>Create something fans can actually use.</h1><p class="lead">Concerto is built around real concert nights, real venues, and real decisions. That leaves room for creators to do more than post an ad: bring taste, personality, and a point of view into something fans use before, during, or after the show.</p><div class="hero-meta"><span class="meta-pill">532K+ views in 90 days</span><span class="meta-pill">97.9% from non-followers</span><span class="meta-pill">341K views on one setlist post</span></div><div class="hero-actions"><a class="btn-primary" href="/contact?topic=creator">Pitch an idea</a><a class="btn-secondary" href="https://instagram.com/theconcertoapp" target="_blank" rel="noopener">Concerto on Instagram</a></div></div></section>
<section class="story-section"><div class="site-shell"><div class="section-head"><p class="eyebrow">Where it lives</p><div><h2>The collaboration can live inside the fan journey.</h2><p>Content is built around a specific tour, venue, city, or concert weekend, not dropped into a feed as a generic sponsorship.</p></div></div><div class="story-grid"><article class="story-card light"><span class="number">Before</span><h3>Help plan the night.</h3><p>The restaurant you would actually pick, the neighborhood worth arriving early for, the venue tip you wish somebody told you.</p></article><article class="story-card sand"><span class="number">Around the show</span><h3>Meet fans in context.</h3><p>Setlist reactions, venue walkthroughs, city guides, and show-week content tied to a real date.</p></article><article class="story-card dark"><span class="number">After</span><h3>Make it memorable.</h3><p>Year-in-review, fan recaps, creator picks, and Concerto Rewind concepts that extend past one post.</p></article></div></div></section>
<section class="section"><div class="shell split"><div><p class="eyebrow">Ideas we like</p><h2>Useful beats generic.</h2></div><div><ul class="clean-list"><li>Creator-curated pre-show picks for a venue or city</li><li>City and venue recommendations from someone who has been</li><li>Concert-night guides and account takeovers</li><li>Giveaways and fan perks around a tour date</li><li>Tour or artist-specific setlist content</li><li>Concerto Rewind campaigns</li></ul><p class="lead" style="margin-top:22px">Creator picks stay clearly labeled as the creator's. Concerto Picks remain Concerto's editorial view, and neither is for sale.</p></div></div></section>
<section class="cta-band"><div class="site-shell"><p class="eyebrow">Who should reach out</p><h2>You do not need millions of followers to have a good idea.</h2><p>Music creators, local city creators, food and travel voices, concert photographers, fan communities, and artists are all welcome. We care about fit and creativity, not a vanity number.</p><div class="hero-actions"><a class="btn-primary" href="/contact?topic=creator">Pitch an idea</a></div></div></section>
</main>''' + page_end()
(ROOT / 'creators.html').write_text(creators)

# ---------------------------------------------------------------- Contact
form = (ROOT / 'scripts/forms/contact.html').read_text()
contact = head('Contact Concerto', 'Reach the right part of Concerto: company, creator, media, and investor inquiries through the form; fan support and partnerships through dedicated channels.', '/contact') + f'''<main>
<section class="page-hero-v4 compact"><div class="site-shell"><p class="eyebrow">Contact</p><h1>Reach the right part of Concerto.</h1><p class="lead">Use the form for company, creator, media, or investor inquiries. Fan support and partnerships have dedicated channels so nothing depends on a personal inbox.</p></div></section>
<section class="section"><div class="shell form-shell"><div><div class="heroCard"><p class="eyebrow">Direct channels</p><h3>Two public inboxes. Clear jobs.</h3><ul><li><b>Fan support:</b> support@concertocity.com, or the Help Center for answers now.</li><li><b>Partnerships:</b> partnerships@concertocity.com, or the interest forms on the Partners pages.</li><li><b>Media, investor, and creator:</b> the form here. It routes by topic.</li></ul></div><div class="hero-actions"><a class="btn-secondary" href="/help">Help Center</a><a class="btn-secondary" href="/partners">Partner forms</a></div></div>{form}</div></section>
</main>''' + page_end()
(ROOT / 'contact.html').write_text(contact)

# ---------------------------------------------------------------- FAQ
qa = json.loads((ROOT / 'scripts/faq.json').read_text())
items = ''.join(f'<details class="card"><summary>{q}</summary><p>{a}</p></details>' for q, a in qa)
ld = {'@context': 'https://schema.org', '@type': 'FAQPage', 'mainEntity': [{'@type': 'Question', 'name': html.unescape(q), 'acceptedAnswer': {'@type': 'Answer', 'text': html.unescape(a)}} for q, a in qa]}
extra = '<script type="application/ld+json">' + json.dumps(ld).replace('</', '<\\/') + '</script>'
faq = head('FAQ | Concerto', 'How Concerto works, what stays free, how Your Night and Perks fit in, what Concerto+ adds, and what verified means.', '/faq', extra) + f'''<main>
<section class="page-hero-v4 compact"><div class="site-shell"><p class="eyebrow">FAQ</p><h1>Answers without the scavenger hunt.</h1><p class="lead">How Concerto works, what stays free, how Your Night and Perks fit in, and what Concerto+ adds. For step-by-step help, use the Help Center.</p><div class="hero-actions"><a class="btn-secondary" href="/help">Help Center</a><a class="btn-secondary" href="/contact">Contact</a></div></div></section>
<section class="section"><div class="shell"><div class="faq-list">{items}</div></div></section>
<section class="cta-band"><div class="site-shell"><p class="eyebrow">Still stuck</p><h2>Talk to a real person.</h2><p>Fan support answers at support@concertocity.com. Partners and media have their own channels on the Contact page.</p><div class="hero-actions"><a class="btn-primary" href="/contact">Contact Concerto</a></div></div></section>
</main>''' + page_end()
(ROOT / 'faq.html').write_text(faq)
print('built about, creators, contact, faq')
