#!/usr/bin/env python3
from pathlib import Path
import html, sys
ROOT=Path(__file__).resolve().parent.parent
sys.path.insert(0,str(ROOT/'scripts'))
from public_chrome import header_html, page_end, HEAD_ASSETS, product_screen
SITE='https://concertocity.com'; APP='https://apps.apple.com/us/app/concerto-show-go/id6744903414'
def e(x): return html.escape(str(x),quote=True)
def head(title,desc,canonical): return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="apple-itunes-app" content="app-id=6744903414"><title>{e(title)}</title><meta name="description" content="{e(desc)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="{SITE+canonical}"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(desc)}"><meta property="og:type" content="website"><meta property="og:url" content="{SITE+canonical}"><meta property="og:image" content="{SITE}/ConcertoSocialPreview.png"><meta property="og:site_name" content="Concerto"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="{SITE}/ConcertoSocialPreview.png"><link rel="icon" href="/favicon.ico" sizes="any"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="apple-touch-icon" href="/apple-touch-icon.png">{HEAD_ASSETS}</head><body class="public-site">'''+header_html(canonical)
def end(): return page_end()
def phone(src,alt): return f'''<div class="device-stage single" aria-label="Concerto app preview"><div class="device"><div class="iphone-screen"><img src="{product_screen(src)}" width="1206" height="2622" alt="{e(alt)}"></div></div></div>'''
def feature_page(slug,eyebrow,title,desc,visual,sections,secondary='/venues'):
 cards=''.join(f'''<article class="story-card {klass}"><span class="number">{num}</span><h3>{h}</h3><p>{p}</p>{('<a class="mini-link" href="'+href+'">'+link+' →</a>') if href else ''}</article>''' for num,h,p,klass,href,link in sections)
 return head(f'{title} | Concerto',desc,'/'+slug)+f'''<main><section class="hero-public"><div class="site-shell wide hero-grid"><div class="hero-copy"><p class="eyebrow">{eyebrow}</p><h1>{title}</h1><p class="lead">{desc}</p><div class="hero-actions"><a class="btn-primary" href="{APP}">Get Concerto →</a><a class="btn-secondary" href="{secondary}">Browse venue guides</a></div></div>{phone(visual,title+' in Concerto')}</div></section><section class="story-section"><div class="site-shell"><div class="section-head"><p class="eyebrow">How it works</p><div><h2>Useful in the moment it matters.</h2><p>Concerto keeps the experience simple: find the information, understand the context, then carry it into Your Night when you save a show.</p></div></div><div class="story-grid">{cards}</div></div></section><section class="cta-band"><div class="site-shell"><p class="eyebrow">From the Concert to the City®</p><h2>Know the night before you leave.</h2><p>Venue facts stay connected to the rest of the show instead of living in another tab.</p><div class="hero-actions" style="justify-content:center"><a class="btn-primary" href="{APP}">Get the App →</a><a class="btn-secondary" href="/venues">Explore venues</a></div></div></section></main>'''+end()

near=head('Concerts Near Me | Concerto','Discover live music around you, then connect the show to venue information, setlists, nearby places, and Your Night in Concerto.','/near-me')+f'''<main><section class="hero-public"><div class="site-shell wide hero-grid"><div class="hero-copy"><p class="eyebrow">Live near you</p><h1>Find the show. Then plan the night.</h1><p class="lead">Near Me turns your location and date into a cleaner way to discover live music, then keeps the venue, setlist, and city around the show connected once you save it.</p><div class="hero-actions"><a class="btn-primary" href="{APP}">Use Near Me in the app →</a><a class="btn-secondary" href="/tours">Browse tours</a></div></div>{phone('near-me','Concerto Near Me screen')}</div></section><section class="story-section"><div class="site-shell"><div class="section-head"><p class="eyebrow">Near Me</p><div><h2>Discovery that doesn’t end at the event card.</h2><p>Use location and timing to find live music, then move directly into the concert context that matters: venue rules, setlist, nearby places, weather, and getting there.</p></div></div><div class="story-grid"><article class="story-card light"><span class="number">01 · Find</span><h3>See what’s happening around you.</h3><p>Start with your location, date, and the kind of event you want.</p></article><article class="story-card sand"><span class="number">02 · Save</span><h3>Make the show yours.</h3><p>A saved event becomes a countdown and a show-specific Your Night destination.</p></article><article class="story-card"><span class="number">03 · Go</span><h3>Carry the context with you.</h3><p>The venue, setlist, nearby places, and timing stay connected to the same night.</p></article></div></div></section><section class="cta-band"><div class="site-shell"><p class="eyebrow">One show. One connected night.</p><h2>Discovery should lead somewhere useful.</h2><p>Near Me finds the event. Concerto carries the rest of the night from there.</p><div class="hero-actions" style="justify-content:center"><a class="btn-primary" href="{APP}">Get Concerto →</a></div></div></section></main>'''+end()
(ROOT/'near-me.html').write_text(near)



yn_steps=[
 ('your-night','This show, in one place','Artist, tour, venue, date, and the countdown. Up Next tells you what matters right now based on how close the show is. Concerto+ Plan My Night starts here.'),
 ('venue-essentials','Venue Essentials','Bag policy, entrances, re-entry, ticket pickup, concessions, and accessibility, each with the official source and the date Concerto last checked it.'),
 ('getting-there','Getting There and the setlist','Directions, Uber, and Lyft in one tap, verified parking and rideshare guidance, then the current setlist so you know the songs before the lights go down.'),
 ('around-venue','Around the venue','Restaurants, hotels, and things to do for this show and this venue, not your current location. Before the show, your stay, the night out.'),
 ('getting-home','Getting Home','Official rideshare guidance, pickup zones when the venue publishes them, and the ride home ready before the encore.'),
]
def yn_step(i,name,title,body,flip=False):
    return f'''<div class="yn-step{' flip' if flip else ''}"><div class="yn-step-copy"><span class="number">0{i}</span><h3>{e(title)}</h3><p>{e(body)}</p></div><div class="yn-step-phone">{phone(name,title+' in Your Night')}</div></div>'''
your_night=head('Your Night | One Show, One Connected Night | Concerto','Your Night is the show-specific home for every concert you save in Concerto: venue essentials, weather, getting there, parking, setlist, nearby places, Concerto Perks, and getting home, in one place.','/your-night')+f'''<main>
<section class="hero-public"><div class="site-shell wide hero-grid"><div class="hero-copy"><p class="eyebrow">Your Night</p><h1>Home tells you where you are going. Your Night tells you everything about that night.</h1><p class="lead">Save a show and Home keeps it simple: your next concert, the countdown, and one action, View Your Night. Tap it and every part of that specific night is already in one place.</p><div class="hero-actions"><a class="btn-primary" href="{APP}">Get Concerto for iPhone</a><a class="btn-secondary" href="/premium">See Concerto+</a></div></div>{phone('home','Concerto Home with Your Next Show and the View Your Night action')}</div></section>
<section class="story-section yn-flow"><div class="site-shell"><div class="section-head"><p class="eyebrow">One connected flow</p><div><h2>Everything for this show, in the order the night happens.</h2><p>Your Night is built from the same verified venue data, live weather, tour and setlist information, and nearby places that power the rest of Concerto, arranged around the concert you actually saved. Scroll it once and you know the night.</p></div></div><div class="yn-steps">{''.join(yn_step(i+1,*st,flip=i%2==1) for i,st in enumerate(yn_steps))}</div></div></section>
<section class="section dark"><div class="shell split"><div><p class="eyebrow">Concerto Perks in Your Night</p><h2>A Perk shows up at the moment it is useful, not in a coupon directory.</h2></div><div><p class="lead">Concerto Perks come from Concerto Partners. The full list lives under Account, but the place they matter is Your Night, where each one is placed inside the part of the night it belongs to.</p><ul class="clean-list"><li><b>Restaurant Perk</b>: Before the Show, beside Restaurants around the venue</li><li><b>Venue Perk</b>: At the Venue, at the top of Venue Essentials</li><li><b>Hotel Perk</b>: Your Stay, beside Hotels and again in Getting Home</li><li><b>Artist or tour Perk</b>: This Tour, right under Up Next for that show</li></ul><p class="lead" style="margin-top:20px">Every Perk is labeled Concerto Partner. Until a partner creates one for your show, the space stays empty rather than filled with filler.</p><div class="hero-actions"><a class="btn-secondary" style="border-color:rgba(255,255,255,.3);color:#fff;background:transparent" href="/perks">How Perks work</a><a class="btn-secondary" style="border-color:rgba(255,255,255,.3);color:#fff;background:transparent" href="/partners">Become a Partner</a></div></div></div></section>
<section class="section"><div class="shell split"><div><p class="eyebrow">Free and Concerto+</p><h2>Your Night is free. Planning it is Concerto+.</h2></div><div><p class="lead">Everything above is free with a saved show. Concerto+ adds Plan My Night on top: dinner, when to leave, arrival, parking, and the ride home turned into one timeline around this exact show, adjusted when weather or timing changes.</p><div class="hero-actions"><a class="btn-primary" href="/premium">See Concerto+</a><a class="btn-secondary" href="/help#help-your-night">Your Night in the Help Center</a></div></div></div></section>
<section class="cta-band"><div class="site-shell"><p class="eyebrow">From the Concert to the City®</p><h2>Save the show. The night is already organized.</h2><p>One card on Home. One tap. Everything about that night.</p><div class="hero-actions"><a class="btn-primary" href="{APP}">Get Concerto for iPhone</a><a class="btn-secondary" href="/venues">Browse venue guides</a></div></div></section>
</main>'''+end()
(ROOT/'your-night.html').write_text(your_night)

pages={
'bagcheck':('Concerto+ · AI Bag Check','Check the bag before the door.','Use AI Bag Check to compare what you plan to bring against the published bag policy for your venue. It helps you prepare; the venue always makes the final entry decision.','bagcheck',[
('01 · Start','Pick the venue.','Bag Check begins with the same verified venue policy used throughout Concerto.','light','/venues','Browse venues'),('02 · Compare','Show Concerto the bag.','Use the app to compare your bag against the venue’s published limits and rules.','sand','', ''),('03 · Decide','Leave with context.','Concerto explains the match and the uncertainty instead of pretending it can guarantee entry.','','/premium','Meet Concerto+')]),
'bags':('Venue intelligence','Bag policies, without the hunt.','Concerto organizes published venue bag rules into clear, dated guides so you can find the answer before you leave.','bags',[
('01 · Verified','Official sources first.','Critical bag rules are researched from venue-published guidance whenever available.','light','/venues','Browse venues'),('02 · Dated','See when it was checked.','Verification dates make it clear when Concerto last confirmed critical information.','sand','',''),('03 · Connected','Attached to Your Night.','The policy stays with the show instead of becoming another screenshot or browser tab.','','/bagcheck','Try AI Bag Check')]),
'parking':('Venue intelligence','Parking that starts with the venue.','Find official parking guidance, named lots, and venue-specific notes inside Concerto venue guides.','parking',[
('01 · Official','Start with venue guidance.','Concerto prioritizes parking information published by the venue or its official partners.','light','/venues','Browse venues'),('02 · Practical','Know what is actually named.','Lots, garages, reservations, and arrival notes are surfaced when they are published.','sand','',''),('03 · Connected','Keep it with the show.','Parking lives alongside the rest of Your Night instead of in a separate planning thread.','','/near-me','Explore Near Me')]),
'rideshare':('Venue intelligence','Know where the ride should go.','Concerto surfaces official rideshare, pickup, and drop-off guidance when venues publish it, and says when a dedicated zone cannot be confirmed.','rideshare',[
('01 · Arrival','Get to the right place.','Use venue-specific pickup and drop-off notes instead of guessing from the pin alone.','light','/venues','Browse venues'),('02 · Honesty','No invented zones.','If a venue has not published a dedicated rideshare area, Concerto says so.','sand','',''),('03 · Getting home','Plan the exit too.','Rideshare context becomes part of the full night, including how you get home.','','/premium','Meet Concerto+')]),
'concessions':('Venue intelligence','Know what is inside.','Concerto organizes published food, drink, and concession information so the venue experience is easier to understand before you arrive.','concessions',[
('01 · Venue first','Published options.','Food, drink, cashless policies, and notable stands are included when the venue confirms them.','light','/venues','Browse venues'),('02 · Useful','Skip the generic filler.','Concerto focuses on information that can actually change your plan for the night.','sand','',''),('03 · Connected','Before and inside.','Concessions can sit beside nearby dining and Your Night context without mixing the two.','','/near-me','Explore nearby')])
}
for slug,(ey,title,desc,vis,secs) in pages.items(): (ROOT/f'{slug}.html').write_text(feature_page(slug,ey,title,desc,vis,secs))
print('built V6 public feature pages + Your Night')
