#!/usr/bin/env python3
"""Partners hub, four partner pages, Perks, Concerto+, Investors, Press.

Every partner page shows the partnership the way a fan would meet it in the
app: an in-app preview rendered from the app's own design system (the Home
Perk card in src/components/HomeCards.tsx and the Your Night rows), the
three-front value standard, placements, and the Netlify interest form kept in
scripts/forms/<type>.html.
"""
import html, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / 'scripts'))
from public_chrome import header_html, page_end, HEAD_ASSETS, product_screen, photo_slot, APP, SITE

def e(x): return html.escape(str(x or ''), quote=True)

def head(title, desc, canonical, extra=''):
    return (f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
            f'<meta name="apple-itunes-app" content="app-id=6744903414"><title>{e(title)}</title><meta name="description" content="{e(desc)}">'
            f'<meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="{SITE+canonical}">'
            f'<meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(desc)}"><meta property="og:type" content="website">'
            f'<meta property="og:url" content="{SITE+canonical}"><meta property="og:image" content="{SITE}/ConcertoSocialPreview.png"><meta property="og:site_name" content="Concerto">'
            f'<meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="{SITE}/ConcertoSocialPreview.png">'
            f'<link rel="icon" href="/favicon.ico" sizes="any"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="apple-touch-icon" href="/apple-touch-icon.png">'
            f'{HEAD_ASSETS}{extra}</head><body class="public-site">') + header_html(canonical)

def phone(name, alt):
    return f'<div class="device"><div class="iphone-screen"><img src="{product_screen(name)}" width="941" height="2048" alt="{e(alt)}" loading="lazy"></div></div>'

# ---------------------------------------------------------------- in-app preview
def app_preview(show, venue, partner, offer, sub, place='home'):
    """Home-style Perk card exactly as HomeCards.tsx renders it, inside a phone."""
    return f'''<div class="device app-preview" aria-label="How this partnership appears in Concerto"><div class="iphone-screen ap-screen">
<div class="ap-status"><span>12:00</span><span class="ap-status-icons"><i class="ap-signal"></i><i class="ap-wifi"></i><i class="ap-battery"></i></span></div>
<div class="ap-greeting">GOOD EVENING</div><div class="ap-lockup"><img src="/img/lockup.png" alt=""></div>
<div class="ap-next"><div class="ap-kicker">YOUR NEXT SHOW</div><div class="ap-show">{e(show)}</div><div class="ap-venue">{e(venue)} · Doors 7:30 PM</div><div class="ap-count"><span><b>12</b>DAYS</span><span class="ap-colon">:</span><span><b>04</b>HRS</span><span class="ap-colon">:</span><span><b>21</b>MIN</span></div></div>
<div class="ap-perk"><div class="ap-perk-top"><span class="ap-gift"></span><span class="ap-perk-kicker">CONCERTO PERK NEAR YOUR SHOW</span><span class="ap-partner">PARTNER</span></div><div class="ap-perk-name">{e(partner)}</div><div class="ap-perk-offer">{e(offer)}</div><div class="ap-perk-sub">{e(sub)}</div><div class="ap-perk-link">View Perk <span>→</span></div></div>
<div class="ap-rail-head"><span>Nearby Restaurants</span><span class="ap-rail-link">View venue</span></div><div class="ap-chips"><span>{e(venue)}</span><span>Filter</span></div><div class="ap-nearby"><div class="ap-near ap-near-photo"><b>{e(partner)}</b><span>Cafe · 6 min</span></div><div class="ap-near ap-near-mono"><i>7</i><b>7th Street Tavern</b><span>Bar · 4 min</span></div></div>
<div class="ap-tabs"><span class="on">Home</span><span>Venues</span><span>Tours</span><span>Near Me</span><span>Account</span></div>
</div></div>'''

def preview_block(kind, show, venue, partner, offer, sub, placements):
    tiles = ''.join(f'<div class="placement"><span>{e(k)}</span><h3>{e(t)}</h3><p>{e(p)}</p></div>' for k, t, p in placements)
    return f'''<section class="section dark preview-section"><div class="shell preview-layout"><div class="preview-copy"><p class="eyebrow">How it appears in Concerto</p><h2>Fans meet the offer where the decision happens.</h2><p class="lead">This is the Home card a fan sees when a Concerto Partner has a real benefit near their saved show. The same offer carries into Your Night, the venue page, and Concerto Perks. Paid placements are always labeled Partner.</p><div class="placement-grid two">{tiles}</div><p class="preview-note">Rendered from the app's design system with example content. Your live placement uses your name, your offer, and your action.</p></div><div class="preview-phone">{app_preview(show, venue, partner, offer, sub)}</div></div></section>'''

# ---------------------------------------------------------------- partner pages
PARTNERS = {
 'restaurants': dict(
    label='Restaurant partnerships', title='Turn concert nights into restaurant guests.',
    desc='Concerto places a useful restaurant offer inside the moment a fan is deciding where to eat before or after a nearby show, then distributes it across the app, website, and social.',
    show='Jonas Brothers', venue='American Airlines Center', partner='Pax & Beneficia', offer='Free espresso with any pre-show order', sub='6 min walk · Show this card at the counter',
    fans=['An exclusive discount, complimentary item, prix-fixe concert menu, or priority reservation window','A place that makes sense for the venue, timing, and night','Clear disclosure when a placement is paid'],
    you=['Show-night demand from fans already going nearby','Reservation and directions actions tied to the campaign','Contextual visibility instead of generic ad impressions'],
    concerto=['Paid sponsorship, an exclusive offer, hosted value, or priority inventory','Permission to activate across agreed app, web, and social surfaces','A trackable offer or action whenever possible'],
    placements=[('01','Your Night','While a saved-show fan is choosing dinner or a post-show stop.'),('02','Around the venue','Near the venue with distance, context, offer, and action.'),('03','Concerto Perks','A dedicated fan-facing home for the offer.'),('04','Social','Show-night creative, giveaways, or venue-specific content.')],
    examples=[('Pre-show prix fixe','A two-course concert menu timed to doors, with a reservation link inside Your Night.'),('Post-show late night','A late-night offer that surfaces after the encore, when fans are deciding where to go.'),('Sponsored venue guide','Your restaurant as the named dining partner on a venue page fans read before they leave.')]),
 'hotels': dict(
    label='Hotel partnerships', title='Be the hotel for the show, not just the city.',
    desc='Concerto connects hotel inventory and fan benefits to the exact show, venue, and date a fan is planning around, from the ticket through the night home.',
    show='Ariana Grande', venue='Kia Forum', partner='Hotel Fairmont Century Plaza', offer='Concert rate plus 2 PM late checkout', sub='9 min drive · Book through Concerto',
    fans=['A concert rate, late checkout, parking credit, or a welcome perk','A hotel chosen for the venue and the night, not a generic listing','Clear disclosure when a placement is paid'],
    you=['High-intent bookings tied to a specific event date','A booking action inside Your Night and the venue page','Visibility across tour-date demand you cannot reach through search alone'],
    concerto=['A real fan rate or benefit, an inventory block, or paid sponsorship','Permission to promote the partnership across app, web, and social','A trackable booking link'],
    placements=[('01','Your Night','Where to stay, placed beside timing, weather, and getting home.'),('02','Venue page','The named stay partner for a venue fans research early.'),('03','Tour pages','Tour-date demand across markets you serve.'),('04','Concerto Perks','A fan-facing home for the concert rate.')],
    examples=[('Show-night rate','A rate that only exists for fans with a saved show at a nearby venue.'),('Late checkout','A small benefit that matters after a late encore, surfaced the morning after.'),('Tour-market package','One offer that follows a tour across your properties in each city.')]),
 'venues': dict(
    label='Venue partnerships', title='Your official information, in the hands of every fan.',
    desc='Concerto already carries verified guides for 346 venues. Official partners get direct control of what fans see, plus placements for parking, concessions, and premium experiences.',
    show='Noah Kahan', venue='Bridgestone Arena', partner='Bridgestone Arena', offer='Official: pre-purchase parking, 20% off garage rates', sub='Official venue partner · Verified today',
    fans=['Venue information that is official, current, and dated','Parking, concessions, and premium offers before they arrive','Fewer surprises at the door'],
    you=['Fewer bad-information calls and fewer bag-policy incidents at the gate','Parking, premium, and F&B actions from fans planning ahead','A direct channel to fans with a saved show at your venue'],
    concerto=['A named official contact for verification and updates','Official parking, premium, or concession offers, or paid sponsorship','Permission to label the guide Official Partner'],
    placements=[('01','Venue guide','The official partner mark and your live information.'),('02','Your Night','Parking and premium offers placed at the arrival step.'),('03','AI Bag Check','Your published policy powering the pre-check.'),('04','Concerto Perks','Official venue offers in one place.')],
    examples=[('Official guide','Your bag policy, gates, and parking marked official and updated by your team.'),('Pre-purchase parking','A parking link at the exact step a fan plans arrival.'),('Premium upsell','Suites, lounges, or fast lane placed in Your Night for fans already going.')]),
 'artists': dict(
    label='Artist and tour partnerships', title='Make every tour date feel planned around the fan.',
    desc='Concerto tracks 158 tours and 56 live setlists. Artist and tour partners can add official setlists, presale and VIP benefits, merch, and city-specific moments across the run.',
    show='Harry Styles', venue='Madison Square Garden', partner='Together, Together Tour', offer='Fan presale code plus early merch access', sub='Official tour partner · Valid for tonight',
    fans=['Official setlists and tour news inside the show they saved','Presale, VIP, or merch benefits that are real and easy to use','A night that feels connected to the artist, not just the venue'],
    you=['Reach fans in every market on the tour, tied to a specific date','Presale, VIP, and merch actions from fans already planning to attend','Setlist and tour-page search demand that already exists on Concerto'],
    concerto=['Official setlist or tour information','A fan benefit, inventory, or paid sponsorship','Permission to label the tour guide Official'],
    placements=[('01','Tour page','Official mark, setlist, dates, and your fan benefit.'),('02','Your Night','Presale, VIP, and merch at the right moment before the show.'),('03','Setlist page','Search demand from fans checking the setlist before they go.'),('04','Social','Setlist and show-night content across the tour.')],
    examples=[('Official setlist','A setlist your team confirms, marked official on the tour and setlist pages.'),('Presale moment','A presale code delivered inside Your Night for fans following the tour.'),('Merch drop','A city-specific merch or VIP offer that appears the day of the show.')]),
}

def three_front(p):
    def col(title, kicker, items):
        lis = ''.join(f'<li>{e(x)}</li>' for x in items)
        return f'<article class="card"><p class="kicker">{kicker}</p><h3>{title}</h3><ul class="clean-list">{lis}</ul></article>'
    return f'''<section class="section"><div class="shell"><p class="eyebrow">The three-front standard</p><h2>Every partnership has to work for the fan, for you, and for Concerto.</h2><div class="grid3">{col('A reason to care.','What fans get',p['fans'])}{col('A useful commercial outcome.','What you get',p['you'])}{col('A real contribution.','What Concerto looks for',p['concerto'])}</div></div></section>'''

def examples(p):
    cards = ''.join(f'<article class="card"><h3>{e(t)}</h3><p>{e(d)}</p></article>' for t, d in p['examples'])
    return f'<section class="section"><div class="shell"><p class="eyebrow">Ways to start</p><h2>Three partnerships we can launch this season.</h2><div class="grid3">{cards}</div></div></section>'

def partner_page(slug, p):
    form = (ROOT / 'scripts/forms' / f'{slug}.html').read_text()
    canonical = f'/partners/{slug}'
    other = ''.join(f'<a class="coming-card" href="/partners/{k}"><strong>{e(v["label"])}</strong><span>{e(v["title"])}</span></a>' for k, v in PARTNERS.items() if k != slug)
    return head(f'{p["label"]} | Concerto Partners', p['desc'], canonical) + f'''<main>
<section class="hero-public"><div class="site-shell wide hero-grid"><div class="hero-copy"><p class="eyebrow">{e(p['label'])}</p><h1>{e(p['title'])}</h1><p class="lead">{e(p['desc'])}</p><div class="hero-actions"><a class="btn-primary" href="#interest">Express interest</a><a class="btn-secondary" href="/partners">All partner types</a></div></div><div class="device-stage single">{app_preview(p['show'], p['venue'], p['partner'], p['offer'], p['sub'])}</div></div></section>
{three_front(p)}
{preview_block(slug, p['show'], p['venue'], p['partner'], p['offer'], p['sub'], p['placements'])}
{examples(p)}
<section class="section" id="interest"><div class="shell form-shell"><div><p class="eyebrow">Express interest</p><h2>Tell us what you would bring.</h2><p class="lead">Partnerships go to partnerships@concertocity.com. We reply to every serious inquiry with a placement plan and what it would take to launch.</p><p class="lead" style="margin-top:14px">Concerto Picks stay editorial and are never for sale. Partner placements are always labeled.</p></div>{form}</div></section>
<section class="setlist-section alt"><div class="site-shell"><div class="catalog-intro"><h2>Other partner types.</h2></div><div class="coming-grid related-grid" style="grid-template-columns:repeat(3,minmax(0,1fr))">{other}</div></div></section>
</main>''' + page_end()

for slug, p in PARTNERS.items():
    (ROOT / f'partner-{slug}.html').write_text(partner_page(slug, p))

# ---------------------------------------------------------------- partners hub
hub_cards = ''.join(f'<a class="rail-card partner-type" href="/partners/{k}"><div class="rail-body"><span class="tag">{e(v["label"])}</span><h3>{e(v["title"])}</h3><p>{e(v["desc"])}</p><span class="mini-link">See how it works</span></div></a>' for k, v in PARTNERS.items())
partners = head('Concerto Partners | Restaurants, Hotels, Venues, Artists', 'Concerto Partners create real fan benefits placed where concert intent already exists: the saved show, the venue, and the night around it. Restaurants, hotels, venues, and artists.', '/partners') + f'''<main>
<section class="page-hero-v4"><div class="site-shell"><p class="eyebrow">Concerto Partners</p><h1>Meet fans at the moment the night is being planned.</h1><p class="lead">Concerto reaches people who already have concert intent: a specific show, a specific venue, a specific city, a specific date. Partners create a real fan benefit and Concerto places it where the decision happens, in the app, on the website, and across social.</p><div class="hero-meta"><span class="meta-pill">532K+ social views in 90 days</span><span class="meta-pill">97.9% of views from non-followers</span><span class="meta-pill">153K Google Search impressions in 12 months</span></div><div class="hero-actions"><a class="btn-primary" href="#types">Choose a partnership</a><a class="btn-secondary" href="/perks">See Concerto Perks</a></div></div></section>
<section class="story-section"><div class="site-shell"><div class="section-head"><p class="eyebrow">The standard</p><div><h2>Every partnership has to work on three fronts.</h2><p>The fan gets a meaningful benefit. The partner gets measurable, high-intent action. Concerto gets a sustainable relationship worth building around. If any side loses, it is not a Concerto partnership.</p></div></div><div class="story-grid"><article class="story-card light"><span class="number">Fans get</span><h3>A reason to care.</h3><p>A useful discount, access, rate, or experience placed around the show they saved, and never disguised as editorial.</p></article><article class="story-card dark"><span class="number">Partners get</span><h3>High-intent distribution.</h3><p>Fans who already know the venue, the date, and the plan. Actions you can measure: reservations, bookings, parking, presales, directions.</p></article><article class="story-card sand"><span class="number">Concerto gets</span><h3>Value worth building around.</h3><p>Paid sponsorship, exclusive offers, official information, inventory, or experiences that make the product better for fans.</p></article></div></div></section>
{photo_slot('venue-exterior','An arena exterior at dusk as fans arrive')}
<section class="discovery" id="types"><div class="site-shell wide"><div class="rail-head"><div><h2>Four ways to partner.</h2><p>Each page shows what fans get, what you get, what Concerto asks for, and exactly how the partnership appears in the app.</p></div></div><div class="card-rail partner-rail">{hub_cards}</div></div></section>
{preview_block('hub', 'Jonas Brothers', 'American Airlines Center', 'Your brand', 'A useful concert-night Perk goes here', 'Clearly labeled. Placed around the show.', [('App','Your Night, venue pages, Home','Placed beside timing, weather, arrival, and the way home.'),('Web','Venue and tour pages','Named placements on pages fans find through search.'),('Perks','Concerto Perks','A dedicated fan-facing home in Account.'),('Social','Campaigns','Show-night creative built around the offer.')])}
<section class="section"><div class="shell split"><div><p class="eyebrow">What Concerto can offer</p><h2>Placement, targeting, and promotion around a real night.</h2></div><div><ul class="clean-list"><li>App placement in Your Night, venue pages, tour pages, and Home</li><li>Website placement on venue, tour, and setlist pages that already rank</li><li>Contextual targeting by show, venue, city, and date</li><li>Social promotion and co-branded campaigns</li><li>Concerto Perks, a labeled fan-facing home for the benefit</li><li>Measurable traffic and actions, reported back to you</li></ul><p class="lead" style="margin-top:22px">Concerto Picks remain editorial and cannot be purchased. Paid relationships are always labeled Partner.</p></div></div></section>
<section class="cta-band"><div class="site-shell"><p class="eyebrow">Start a partnership</p><h2>Something useful has to happen for all three sides.</h2><p>Pick the partnership that fits and tell us what you would bring. We reply with a placement plan.</p><div class="hero-actions"><a class="btn-primary" href="/partners/restaurants">Restaurants</a><a class="btn-secondary" href="/partners/hotels">Hotels</a><a class="btn-secondary" href="/partners/venues">Venues</a><a class="btn-secondary" href="/partners/artists">Artists and tours</a></div></div></section>
</main>''' + page_end()
(ROOT / 'partners.html').write_text(partners)

# ---------------------------------------------------------------- perks
perks = head('Concerto Perks | Benefits Built Around the Show', 'Concerto Perks are partner-created benefits placed where they are useful around a concert night: before the show, at the venue, and after. Found in the app under Account.', '/perks') + f'''<main>
<section class="hero-public"><div class="site-shell wide hero-grid"><div class="hero-copy"><p class="eyebrow">Concerto Perks</p><h1>Perks that belong to the night.</h1><p class="lead">Exclusive benefits created with Concerto Partners and surfaced when they are actually useful: around your show, your venue, and your city. Not a coupon wall, and never disguised as a recommendation.</p><div class="hero-actions"><a class="btn-primary" href="{APP}">Get Concerto for iPhone</a><a class="btn-secondary" href="/partners">Become a partner</a></div><div class="hero-proof"><div class="proof"><strong>Before</strong><span>dinner, stays, parking</span></div><div class="proof"><strong>At</strong><span>venue and artist offers</span></div><div class="proof"><strong>After</strong><span>late night, the way home</span></div></div></div><div class="device-stage single">{app_preview('Jonas Brothers', 'American Airlines Center', 'Pax & Beneficia', 'Free espresso with any pre-show order', '6 min walk · Show this card at the counter')}</div></div></section>
<section class="story-section"><div class="site-shell"><div class="section-head"><p class="eyebrow">Where Perks live</p><div><h2>In Account, and around the show you saved.</h2><p>The full Perks view is in the app under Account. A Perk only appears on Home, in Your Night, or on a venue page when it is tied to the show you are actually going to.</p></div></div><div class="story-grid"><article class="story-card light"><span class="number">Before the show</span><h3>Dinner, stays, arrival.</h3><p>Restaurant offers, reservation windows, concert hotel rates, late checkout, and parking placed where you plan them.</p></article><article class="story-card sand"><span class="number">At the show</span><h3>Venue and artist benefits.</h3><p>Official venue offers, merch or concession benefits, presale and VIP access, and fan experiences when they exist.</p></article><article class="story-card dark"><span class="number">After the show</span><h3>Keep the night moving.</h3><p>Late-night dining, hotel benefits, and the way home, tied to the venue and the time the encore ends.</p></article></div></div></section>
<section class="section"><div class="shell split"><div><p class="eyebrow">The rules</p><h2>No fake inventory. No hidden sponsors.</h2></div><div><ul class="clean-list"><li>A Perk appears only when a real partner has created a real fan benefit.</li><li>Paid placements are always labeled Partner.</li><li>Concerto Picks are editorial and are never for sale. Perks and Picks never mix.</li><li>A Perk is tied to a show, venue, or city. It is not a feed.</li><li>Until a real Perk exists near your show, the space stays empty rather than filled with filler.</li></ul></div></div></section>
<section class="cta-band"><div class="site-shell"><p class="eyebrow">For businesses</p><h2>Create a Perk fans will actually use.</h2><p>Restaurants, hotels, venues, and artists can build a benefit around a real night and reach fans who already have a ticket.</p><div class="hero-actions"><a class="btn-primary" href="/partners">See partnership options</a></div></div></section>
</main>''' + page_end()
(ROOT / 'perks.html').write_text(perks)

# ---------------------------------------------------------------- Concerto+
night_rows = [('5:45 PM','Dinner','Pax & Beneficia, 6 min walk, table for two held until 6:30'),('7:10 PM','Leave for the venue','Traffic and gate lines are already built in'),('7:30 PM','Doors','Bag policy checked. Small clear bag only'),('11:15 PM','Getting home','Rideshare pickup on Victory Ave, not the arena lot')]
night = ''.join(f'<div class="yn-row"><span class="yn-time">{t}</span><div><b>{e(l)}</b><span>{e(d)}</span></div></div>' for t, l, d in night_rows)
compare = [('Verified venue information','Free','Free'),('Tours, setlists, Near Me, search','Free','Free'),('Save shows and countdowns','Free','Free'),('Nearby restaurants, hotels, things to do','Free','Free'),('Your Night, personalized around the show','','Included'),('Plan My Night timing built around doors','','Included'),('AI Bag Check against the venue policy','','Included'),('Contextual alerts when timing or weather changes what matters','','Included')]
compare_rows = ''.join(f'<tr><td>{e(a)}</td><td>{"✓" if b else ""}</td><td class="plus">{"✓" if c else ""}</td></tr>' for a, b, c in compare)
premium = head('Concerto+ | Your Whole Night, Planned Around You', 'Free Concerto gives you trusted venue facts and discovery. Concerto+ turns the show you saved, the venue, timing, weather, and nearby places into a personalized plan for the night. $7.99 a month or $69.99 a year.', '/premium', '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Product","name":"Concerto+","description":"Personalized concert-night planning inside the Concerto app.","brand":{"@type":"Brand","name":"Concerto"},"offers":[{"@type":"Offer","price":"7.99","priceCurrency":"USD","url":"https://concertocity.com/premium","name":"Monthly"},{"@type":"Offer","price":"69.99","priceCurrency":"USD","url":"https://concertocity.com/premium","name":"Yearly"}]}</script>') + f'''<main>
<section class="hero-public"><div class="site-shell wide hero-grid"><div class="hero-copy"><p class="eyebrow">Concerto+</p><h1>Your whole night, planned around you.</h1><p class="lead">Free Concerto gives you the facts. Concerto+ takes the show you saved, the venue, the timing, the weather, and what is nearby, and turns them into one plan for the night.</p><div class="hero-actions"><a class="btn-primary" href="{APP}">Start in the app</a><a class="btn-secondary" href="#free">See what stays free</a></div><div class="hero-proof"><div class="proof"><strong>$7.99</strong><span>per month</span></div><div class="proof"><strong>$69.99</strong><span>per year</span></div><div class="proof"><strong>1</strong><span>saved show is all it takes</span></div></div></div><div class="device-stage single">{phone('premium', 'Concerto venue page with AI Bag Check and Plan Night')}</div></div></section>
<section class="story-section"><div class="site-shell"><div class="section-head"><p class="eyebrow">What changes</p><div><h2>Concerto+ removes decisions, not information.</h2><p>Free can show restaurants near the venue. Concerto+ tells you which ones fit before doors. Free shows parking. Concerto+ works backward into a leave time. Free shows weather. Concerto+ adjusts the plan because of it.</p></div></div><div class="story-grid"><article class="story-card light"><span class="number">Timing</span><h3>Know when to move.</h3><p>Dinner, travel, parking, walking, and doors become one realistic timeline around the actual show.</p></article><article class="story-card sand"><span class="number">Context</span><h3>Use what Concerto already knows.</h3><p>Weather, venue rules, nearby places, and show details stop behaving like separate features.</p></article><article class="story-card dark"><span class="number">Confidence</span><h3>Make the next choice easier.</h3><p>AI Bag Check and contextual guidance interpret verified information without hiding the source facts.</p></article></div></div></section>
{photo_slot('dinner','Friends at dinner before a show')}
<section class="section dark"><div class="shell split"><div><p class="eyebrow">Your Night</p><h2>One saved show becomes the plan.</h2><p class="lead">This is the shape of a Concerto+ night. Every row is built from the venue's real information and the show's real timing, then adjusted as the day changes.</p><div class="hero-actions"><a class="btn-primary" style="background:var(--gold);color:var(--navy)!important;border-color:var(--gold)" href="{APP}">Plan your night</a></div></div><div class="yn-card"><div class="yn-head"><span class="ap-kicker">YOUR NIGHT</span><b>Jonas Brothers · American Airlines Center</b><span>Thursday · Rain clearing by 6 PM</span></div>{night}<div class="yn-foot">Built from verified venue data, live weather, and your saved show. Example content.</div></div></div></section>
<section class="section" id="free"><div class="shell"><p class="eyebrow">Free and Concerto+</p><h2>The core Concerto library stays free.</h2><p class="lead">Verified facts stay free for everyone. Personalization and orchestration power Concerto+.</p><div class="compare-wrap"><table class="compare"><thead><tr><th>What you get</th><th>Free</th><th class="plus">Concerto+</th></tr></thead><tbody>{compare_rows}</tbody></table></div></div></section>
<section class="section"><div class="shell"><p class="eyebrow">Questions</p><h2>Before you subscribe.</h2><div class="grid3"><details class="card"><summary>Do I need Concerto+ to use the app?</summary><p>No. Venue guides, tours, setlists, Near Me, saved shows, countdowns, and nearby places are free. Concerto+ adds the personalized plan.</p></details><details class="card"><summary>How is Concerto+ billed?</summary><p>Through your Apple ID at $7.99 a month or $69.99 a year. Cancel any time in iPhone Settings. Access continues to the end of the period.</p></details><details class="card"><summary>Does Concerto+ guarantee entry or timing?</summary><p>No. The plan is built from published venue information and live conditions, and the venue always makes the final call at the door. Concerto+ helps you prepare; it does not replace the venue's rules.</p></details></div></div></section>
<section class="cta-band"><div class="site-shell"><p class="eyebrow">Start in the app</p><h2>Save the show. Concerto+ handles more of the night.</h2><p>Free Concerto gives you what to know. Concerto+ helps you decide what to do with it.</p><div class="hero-actions"><a class="btn-primary" href="{APP}">Get Concerto for iPhone</a><a class="btn-secondary" href="/help">Read the Help Center</a></div></div></section>
</main>''' + page_end()
(ROOT / 'premium.html').write_text(premium)

# ---------------------------------------------------------------- Investors
investors = head('Investors | Concerto', 'Concerto is building the layer around live events: verified venue intelligence, tour and setlist discovery, saved-show context, a premium planning product, and a partner model built on measurable fan value.', '/investors') + f'''<main>
<section class="page-hero-v4"><div class="site-shell"><p class="eyebrow">Investors</p><h1>The concert creates intent. Concerto connects what comes next.</h1><p class="lead">A fan with a saved show is about to decide on transportation, food, lodging, timing, and what to do around a specific venue on a specific date. Concerto is built to meet that intent before it fragments across a dozen unrelated products.</p><div class="hero-actions"><a class="btn-primary" href="/contact?topic=investor">Start a conversation</a><a class="btn-secondary" href="/about">See the company</a></div></div></section>
{photo_slot('stage-lights','Stage lights over a live audience')}
<section class="story-section"><div class="site-shell"><div class="section-head"><p class="eyebrow">The thesis</p><div><h2>The ticket is only the beginning of the spend.</h2><p>Ticketing ends the moment the purchase clears. Everything after it, the venue rules, the parking, the dinner, the hotel, the setlist, the way home, is still scattered across venue sites, maps, review apps, and group chats. Concerto is the product for that gap.</p></div></div><div class="story-grid"><article class="story-card light"><span class="number">Trust</span><h3>Verified venue intelligence.</h3><p>346 structured venue guides, eight verified sections each, researched from official sources and dated. The reason Concerto gets opened when the stakes of the night become real.</p></article><article class="story-card sand"><span class="number">Intent</span><h3>Saved-show context.</h3><p>Once a show is saved, the product knows the venue, city, date, and artist the fan is planning around. That context is the targeting layer.</p></article><article class="story-card dark"><span class="number">Monetization</span><h3>Subscription plus partners.</h3><p>Concerto+ monetizes orchestration at $7.99 a month. Partner campaigns monetize useful local and event-driven value without turning the product into a banner network.</p></article></div></div></section>
<section class="proof-band"><div class="site-shell"><div class="section-head"><p class="eyebrow">Demand signals</p><div><h2>Attention already exists. The next stage is capture.</h2><p>Concerto has demonstrated discovery through social and search before spending on either. These are reach and attention metrics, not users or revenue, and they are the reason the product is worth building distribution on.</p></div></div><div class="traction-grid"><div class="traction"><strong>532K+</strong><span>social views in the last 90 days</span><small>Instagram account insights</small></div><div class="traction"><strong>97.9%</strong><span>of those views from non-followers</span><small>Instagram account insights</small></div><div class="traction"><strong>341K</strong><span>views on a single setlist post</span><small>Instagram</small></div><div class="traction"><strong>153K</strong><span>Google Search impressions over 12 months</span><small>Google Search Console</small></div></div><div class="trust-note"><span>78K+ content interactions and 42K+ accounts engaged in the same 90 days. Follower and download counts are deliberately not the story.</span><a class="text-link" href="/press">Press and media</a></div></div></section>
<section class="section"><div class="shell split"><div><p class="eyebrow">What is built</p><h2>A real product, a shared data engine, and two presentation systems.</h2></div><div><ul class="clean-list"><li>Native iOS app: saved shows, Your Night, venue intelligence, Near Me, Concerto+, AI Bag Check, Perks, alerts</li><li>Public website: 586 crawlable pages sharing the app's venue, tour, and setlist data</li><li>346 venue guides, 158 tour guides, 56 live setlists, 101 tours tracked for setlists</li><li>Concerto+ subscription live through the App Store</li><li>Concerto Partners program with restaurant, hotel, venue, and artist tracks</li><li>Independent from artists, venues, teams, and promoters</li></ul></div></div></section>
<section class="cta-band"><div class="site-shell"><p class="eyebrow">The right network matters</p><h2>Capital helps. Relevant doors change the trajectory.</h2><p>The strongest fit is an investor who sees the live-event utility, the local-commerce opportunity, and the distribution advantage together.</p><div class="hero-actions"><a class="btn-primary" href="/contact?topic=investor">Investor inquiry</a></div></div></section>
</main>''' + page_end()
(ROOT / 'investors.html').write_text(investors)

# ---------------------------------------------------------------- Press
press = head('Press & Media | Concerto', 'Company facts, boilerplate, product imagery, and media contact for Concerto, the concert companion for the show, venue, and city around it.', '/press') + f'''<main>
<section class="page-hero-v4"><div class="site-shell"><p class="eyebrow">Press and media</p><h1>A better night starts with better information.</h1><p class="lead">Concerto is a consumer platform built around what happens after someone decides to go. It brings verified venue information, setlists, nearby discovery, show-night planning, and the way home into one connected experience.</p><div class="hero-actions"><a class="btn-primary" href="/contact?topic=media">Media inquiry</a><a class="btn-secondary" href="/about">About Concerto</a></div></div></section>
<section class="section"><div class="shell split"><div><p class="eyebrow">Boilerplate</p><h2>Concerto, From the Concert to the City®</h2></div><div><p class="lead">Concerto helps fans plan the concert and the night around it. The iPhone app and website combine verified venue logistics for 346 venues, live tour and setlist information, nearby restaurants, hotels, and things to do, and Concerto+ personalized planning. Concerto is independent from artists, venues, teams, and promoters. concertocity.com</p><ul class="clean-list"><li>Founded and operated by Jayce Wells, Dallas-Fort Worth</li><li>Available on iPhone; public guides on the web</li><li>346 researched venue guides, 158 tour guides, 56 live setlists</li><li>Registered slogan: From the Concert to the City®</li></ul></div></div></section>
<section class="story-section"><div class="site-shell"><div class="section-head"><p class="eyebrow">What makes it different</p><div><h2>The product begins where ticketing usually ends.</h2></div></div><div class="story-grid"><article class="story-card light"><span class="number">Trust</span><h3>Verified venue intelligence.</h3><p>Bag policy, parking, rideshare, concessions, accessibility, re-entry, ticket pickup, and gates, researched against official sources and dated.</p></article><article class="story-card sand"><span class="number">Context</span><h3>One night, connected.</h3><p>Save a show and Concerto connects the venue, weather, setlist, nearby places, transportation, and getting-home information around that exact event.</p></article><article class="story-card dark"><span class="number">Personalization</span><h3>Concerto+.</h3><p>The membership turns the information into a personalized plan for when to go, where to stop, what to check, and how to end the night.</p></article></div></div></section>
<section class="section"><div class="shell split"><div><p class="eyebrow">Founder</p><h2>Built from the fan problem outward.</h2></div><div><p class="lead">Jayce Wells founded Concerto after seeing how fragmented concert-night planning remained even after tickets were purchased. The goal is simple: make the night around the concert feel as considered as the concert itself.</p></div></div></section>
<section class="discovery"><div class="site-shell wide"><div class="rail-head"><div><h2>Product imagery.</h2><p>Current app captures, unaltered except for a normalized status bar. Higher-resolution files and the logo lockup are available on request.</p></div></div><div class="product-row"><figure><div class="device"><div class="iphone-screen"><img src="{product_screen('home')}" width="941" height="2048" alt="Concerto Home" loading="lazy"></div></div><figcaption>Home: next show countdown, setlist status, nearby places</figcaption></figure><figure><div class="device"><div class="iphone-screen"><img src="{product_screen('venue')}" width="941" height="2048" alt="Concerto venue page" loading="lazy"></div></div><figcaption>Venue guide with AI Bag Check and Plan Night</figcaption></figure><figure><div class="device"><div class="iphone-screen"><img src="{product_screen('near-me')}" width="941" height="2048" alt="Concerto Near Me" loading="lazy"></div></div><figcaption>Near Me: live music by location and date</figcaption></figure></div></div></section>
<section class="cta-band"><div class="site-shell"><p class="eyebrow">Media contact</p><h2>Screenshots, background, interviews, product access.</h2><p>Use the media inquiry form and we will reply with current imagery, founder background, company facts, and access for editorial review.</p><div class="hero-actions"><a class="btn-primary" href="/contact?topic=media">Media inquiry</a><a class="btn-secondary" href="https://instagram.com/theconcertoapp" target="_blank" rel="noopener">Instagram</a></div></div></section>
</main>''' + page_end()
(ROOT / 'press.html').write_text(press)
print('built partners hub, 4 partner pages, perks, premium, investors, press')
