"""The public experience: a concert-night story, with real, unframed app captures."""
import html
import json
from pathlib import Path
from public_chrome import APP, page_end, product_screen, app_link_campaign

ROOT = Path(__file__).resolve().parent.parent
def e(value): return html.escape(str(value), quote=True)

def capture(key, alt, fallback='your-night'):
    manifest = json.loads((ROOT/'img/product/screens/manifest.json').read_text())
    if key not in manifest:
        key = fallback
        alt = 'Your Night in Concerto, where a saved concert’s planning begins'
    return f'<figure class="product-capture"><img src="{product_screen(key)}" width="1206" height="2622" alt="{e(alt)}" loading="lazy" decoding="async"><figcaption>Inside Concerto · Example app view</figcaption></figure>'

def close(title='Your next show.<br>Make a night of it.'):
    return f'<section class="last-call"><div class="site-shell"><p class="eyebrow">From the Concert to the City®</p><h2>{title}</h2><a class="btn-primary" href="{app_link_campaign("website-footer")}">Get Concerto for iPhone <span aria-hidden="true">↗</span></a><p class="small-print">Free to download. Concerto+ available in the app.</p></div></section>'

def app_gallery():
    views = [('venues', 'Find your venue'), ('tours', 'Explore tours'), ('tour', 'Inside a tour'), ('venue', 'Inside a venue')]
    figures = ''.join(capture(key, title + ' in Concerto').replace('Inside Concerto · Example app view', e(title) + ' · Example app view') for key, title in views)
    return '<section class="app-gallery"><div class="site-shell"><p class="eyebrow">Inside Concerto</p><h2>A closer look.</h2><p class="small-print">Scroll through the app views.</p><div class="app-gallery-rail" tabindex="0" role="region" aria-label="Concerto app screenshots">'+figures+'</div></div></section>'

def journey(first_capture='your-night'):
    phases = [
      ('before','01','Before the show','The anticipation<br>is part of it.','Save your concert. Find the venue essentials, explore nearby dinner spots, and get familiar with the available tour setlist.',first_capture,'Your saved show and the Your Night entry point','/your-night','Meet Your Night'),
      ('there','02','At the venue','Less figuring out.<br>More being there.','Bag rules, entry information, parking, and venue guidance. Keep the useful details close when the crowd starts moving.','venue-essentials','Venue essentials within Your Night','/venues','Explore venue guides'),
      ('after','03','After the encore','Keep the way<br>home handy.','Return to the venue’s published pickup guidance and ride links. Your Night keeps the exit connected to the show.','getting-home','Getting Home guidance in Your Night','/rideshare','Explore getting home'),
    ]
    buttons=''.join(f'<button type="button" id="night-tab-{key}" role="tab" aria-selected="{str(i==0).lower()}" aria-controls="night-panel-{key}" tabindex="{0 if i==0 else -1}" data-night-tab="{key}"><span>{number}</span>{label}<span aria-hidden="true">↗</span></button>' for i,(key,number,label,*_) in enumerate(phases))
    panels=''
    for i,(key,number,label,title,desc,image,alt,href,link) in enumerate(phases):
      panels += f'<div class="night-panel" id="night-panel-{key}" role="tabpanel" aria-labelledby="night-tab-{key}" {"hidden" if i else ""}><div class="night-panel-copy"><p class="eyebrow">Your concert, connected</p><h3>{title}</h3><p>{desc}</p><a class="text-link" href="{href}">{link} <span aria-hidden="true">↗</span></a></div>{capture(image,alt)}</div>'
    return '<section class="night-experience" id="the-night"><div class="site-shell"><div class="section-lead"><p class="eyebrow">One show. The whole night.</p><h2>It all belongs together.</h2></div><div class="night-tabs" role="tablist" aria-label="Explore your concert night">'+buttons+'</div>'+panels+'<noscript><p>Explore <a href="/your-night">Your Night</a>, <a href="/venues">venue guides</a>, and <a href="/rideshare">getting home</a>.</p></noscript></div></section>'

def home_page(head, schema):
    hero=f'''<section class="home-hero poster-hero"><div class="site-shell"><div class="poster-topline"><p class="eyebrow">The concert-night companion</p><span>For the fans. For the whole night.</span></div><h1>Make a night<br><em>of it.</em></h1><div class="poster-bottom"><p>The show you love. The city around it.<br>One app to bring your concert night together.</p><div><a class="btn-primary" href="{app_link_campaign('website-home')}">Get Concerto for iPhone <span aria-hidden="true">↗</span></a><a class="poster-secondary" href="#the-night">Take a look inside <span aria-hidden="true">↓</span></a></div></div><div class="poster-index" aria-hidden="true"><span>BEFORE THE SHOW</span><span>AT THE VENUE</span><span>AFTER THE ENCORE</span></div></div></section>'''
    guides='''<section class="explore-editorial"><div class="site-shell"><div class="section-lead"><p class="eyebrow">Already looking forward to one?</p><h2>Start with<br>your show.</h2><p>Find the useful details here. Keep them with your saved concert in the app.</p></div><div class="explore-links"><a href="/venues"><span class="index-no">01</span><div><h3>Know the venue.</h3><p>Bag policies, entry, parking, and getting home.</p></div><span class="row-arrow" aria-hidden="true">↗</span></a><a href="/tours"><span class="index-no">02</span><div><h3>Follow the tour.</h3><p>Your artist, their tour, and the details around it.</p></div><span class="row-arrow" aria-hidden="true">↗</span></a><a href="/setlists"><span class="index-no">03</span><div><h3>Learn every word.</h3><p>Available setlists and tour playlists, with their sources.</p></div><span class="row-arrow" aria-hidden="true">↗</span></a></div></div></section>'''
    plus='''<section class="plus-editorial"><div class="site-shell"><div><p class="eyebrow">Concerto+</p><h2>A little planning.<br><em>A lot to look<br>forward to.</em></h2></div><div class="plus-editorial-copy"><p>Turn your saved show into a plan for the evening. Dinner, arrival, and the way home—shaped around you.</p><a class="text-link" href="/premium">Explore Concerto+ <span aria-hidden="true">↗</span></a><p class="small-print">Venue guides, available setlists, and Your Night stay free.</p></div></div></section>'''
    return head('Concerto | Everything After the Ticket, in One Place','Save your show. Bring venue guidance, setlists, nearby places, and the way home together with Concerto.','/',schema)+'<main class="experience-home">'+hero+journey('home')+guides+plus+close()+'</main>'+page_end()

def your_night_page(head):
    hero=f'''<section class="type-hero"><div class="site-shell"><p class="eyebrow">Your Night · Free in Concerto</p><h1>The show is yours.<br><em>So is the night.</em></h1><div class="hero-bottom"><p>Save a concert and give the whole evening a home. The venue, the music, the places nearby, and the way back.</p><a class="btn-primary" href="{APP}">Save your next show ↗</a></div></div></section>'''
    free='''<section class="principles-strip"><div class="site-shell"><div><span>01 / SAVE</span><h3>Start with your show.</h3><p>Find a concert and save it. Open Your Night from Home or My Shows.</p></div><div><span>02 / PREPARE</span><h3>Keep the facts close.</h3><p>Check sources and dates on venue guidance. Available details vary by show.</p></div><div><span>03 / MAKE IT YOURS</span><h3>Add a plan with +.</h3><p>Concerto+ adds personalized planning, AI Bag Check, and show-day alerts.</p><a class="text-link" href="/premium">Explore Concerto+ ↗</a></div></div></section>'''
    return head('Your Night | Every Part of Your Show | Concerto','Save a concert and keep venue rules, available setlists, nearby places, and the way home together.','/your-night')+'<main class="experience-product">'+hero+journey()+app_gallery()+close()+'</main>'+page_end()

def premium_page(head):
    schema='<script type="application/ld+json">'+json.dumps({'@context':'https://schema.org','@type':'Product','name':'Concerto+','description':'Personalized concert-night planning inside Concerto.','brand':{'@type':'Brand','name':'Concerto'},'offers':[{'@type':'Offer','price':'7.99','priceCurrency':'USD','url':'https://concertocity.com/premium','name':'Monthly'},{'@type':'Offer','price':'69.99','priceCurrency':'USD','url':'https://concertocity.com/premium','name':'Yearly'}]})+'</script>'
    hero=f'''<section class="type-hero plus-hero"><div class="site-shell"><p class="eyebrow">Concerto+</p><h1>Good plans.<br><em>Great nights.</em></h1><div class="hero-bottom"><p>A plan around your show and your preferences.<br>A little less to figure out before you leave.</p><a class="btn-primary" href="{APP}">Explore Concerto+ in the app ↗</a></div></div></section>'''
    features=f'''<section class="product-story"><div class="site-shell product-story-grid"><div><p class="eyebrow">Your evening, with a plan</p><h2>From dinner<br>to the encore.</h2><p class="lead">Choose what you’re in the mood for. Build a suggested timeline around your concert, adjust the stops and times, and share it with your people.</p><div class="feature-lines"><div><h3>Plan My Night</h3><p>Personalized suggestions using available show and venue information.</p></div><div><h3>AI Bag Check</h3><p>Compare your bag with the venue’s published policy before you go.</p></div><div><h3>Show-day alerts</h3><p>Useful reminders for saved shows, with notification controls in Settings.</p></div></div></div>{capture('night-plan','Concerto app view: a saved show or its suggested night plan','your-night')}</div></section>'''
    pricing=f'''<section class="membership-section"><div class="site-shell"><div><p class="eyebrow">Make room for more of the night</p><h2>Meet your +.</h2><p>The essentials stay free. Add Concerto+ when you want a personal plan.</p></div><div class="membership-terms"><div class="membership-price"><p><b>$7.99</b><span>per month</span></p><p><b>$69.99</b><span>per year</span></p></div><a class="btn-primary" href="{APP}">Choose in the app ↗</a><p class="small-print">US pricing. Confirm current price and terms before purchase. Apple subscriptions renew automatically unless canceled.</p><details><summary>What stays free?</summary><p>Venue guides, available setlists, tours, nearby discovery, saved shows, and Your Night.</p></details><details><summary>What should I know about the plan?</summary><p>Plans are suggestions, not reservations. Confirm times, business availability, and venue rules. AI Bag Check cannot guarantee entry. Saved plans stay on your device; sharing sends a text copy.</p></details><details><summary>How do I manage my subscription?</summary><p>Manage or cancel in your Apple subscription settings. Use Restore Purchases in the app if your membership is missing.</p></details></div></div></section>'''
    return head('Concerto+ | Your Whole Night, Planned Around You','Personalized concert-night planning, AI Bag Check, and show-day alerts with Concerto+.','/premium',schema)+'<main class="experience-product">'+hero+features+pricing+'</main>'+page_end()
