"""The screenshot-free homepage: original concert artwork and useful links."""
from public_chrome import page_end, app_link_campaign
from night_visuals import stage

def home_page(head, schema):
    from experience_pages import journey, close
    hero=f'<section class="home-hero concert-hero"><div class="site-shell"><p class="eyebrow">For the love of live music</p><h1>A great show.<br>A whole night to remember.</h1><p class="concert-intro">The venue. The setlist. The city around it.<br>Bring it together with Concerto.</p><a class="btn-primary" href="{app_link_campaign("website-home")}">Get Concerto for iPhone ↗</a><a class="hero-learn" href="#the-night">Explore the night ↓</a></div>{stage()}</section>'
    guides='''<section class="discovery-section"><div class="site-shell"><div class="section-lead"><p class="eyebrow">Start exploring</p><h2>For the fans who<br>like to know.</h2></div><div class="discovery-grid"><a href="/venues"><span class="discovery-mark" aria-hidden="true">◎</span><h3>The place.</h3><p>Venue guides. Bag rules.<br>Your way in and out.</p><span class="text-link">Explore venues ↗</span></a><a href="/tours"><span class="discovery-mark" aria-hidden="true">↗</span><h3>The artist.</h3><p>Find the tour.<br>Follow what you love.</p><span class="text-link">Explore tours ↗</span></a><a href="/setlists"><span class="discovery-mark" aria-hidden="true">♫</span><h3>Every word.</h3><p>Available setlists and playlists.<br>Get familiar before the lights go down.</p><span class="text-link">Explore setlists ↗</span></a></div></div></section>'''
    plus='''<section class="plus-editorial"><div class="site-shell"><div><p class="eyebrow">Concerto+</p><h2>Less to figure out.<br>More to look<br>forward to.</h2></div><div class="plus-editorial-copy"><p>A personal plan around your show. Dinner, arrival, and the way home—shaped around you.</p><a class="text-link" href="/premium">Meet your + ↗</a><p class="small-print">Your Night, venue guides, and available setlists stay free.</p></div></div></section>'''
    return head('Concerto | Everything After the Ticket, in One Place','Save your show. Bring venue guidance, setlists, nearby places, and the way home together with Concerto.','/',schema)+'<main class="experience-home">'+hero+journey()+guides+plus+close()+'</main>'+page_end()
